### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by TacTicTow** [Jimako-e107-themes/Landing-Zero-2#2]
e_header.php has an error in line 18 that prevents LGSL from working. 

change from

if (e_CURRENT_PLUGIN == 'lgsl')

to

if (!defined('e107_INIT')) { exit; }

**Comment by Jimmi08** [comment]
Hi, this is not correct fix.  e107 has to defined in e_header, this can't be used this way.   
What is your PHP version?  
And what is not working?
And you are testing lgsl 6.2?

**Comment by Jimmi08** [comment]
@TacTicTow not sure if you got notification :)

**Comment by Jimmi08** [comment]
@TacTicTow I found what you mean. I see it when I installed COD Ghost theme and PHP 8.1.   I am closing this because it is lsgl issue or other theme issue.
